q=qreg(10);
psi0=kron(kron(kron(kron(kron(kron(kron(kron(kron(X,X),X),X),X),X),X),X),X),X)*q;
%1h
psi1=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),I),I)*psi0;
%1p
psi2=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/1024))*psi1;
psi2_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),I),H)*psi2;
psi3=CX(0,9)*psi2_5;
psi3_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),I),H)*psi3;
psi4=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/1024),I),I),I),I),I),I),I),I),I)*psi3_5;
psi4_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),I),H)*psi4;
psi5=CX(0,9)*psi4_5;
psi5_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),I),H)*psi5;
psi6=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/1024),I),I),I),I),I),I),I),I),I)*psi5_5;
%2p
psi7=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/512)),I)*psi6;
psi7_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),H),I)*psi7;
psi8=kron(CX(1,9),I)*psi7_5;
psi8_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),H),I)*psi8;
psi9=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/512),I),I),I),I),I),I),I),I),I)*psi8_5;
psi9_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),H),I)*psi9;
psi10=kron(CX(1,9),I)*psi9_5;
psi10_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),I),H),I)*psi10;
psi11=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/512),I),I),I),I),I),I),I),I),I)*psi10_5;
%3p
psi12=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/256)),I),I)*psi11;
psi12_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),H),I),I)*psi12;
psi13=kron(kron(CX(2,9),I),I)*psi12_5;
psi13_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),H),I),I)*psi13;
psi14=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/256),I),I),I),I),I),I),I),I),I)*psi13_5;
psi14_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),H),I),I)*psi14;
psi15=kron(kron(CX(2,9),I),I)*psi14_5;
psi15_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),I),H),I),I)*psi15;
psi16=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/256),I),I),I),I),I),I),I),I),I)*psi15_5;
%4p
psi17=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/128)),I),I),I)*psi16;
psi17_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),H),I),I),I)*psi17;
psi18=kron(kron(kron(CX(3,9),I),I),I)*psi17_5;
psi18_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),H),I),I),I)*psi18;
psi19=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/128),I),I),I),I),I),I),I),I),I)*psi18_5;
psi19_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),H),I),I),I)*psi19;
psi20=kron(kron(kron(CX(3,9),I),I),I)*psi19_5;
psi20_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),I),H),I),I),I)*psi20;
psi21=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/128),I),I),I),I),I),I),I),I),I)*psi20_5;
%5p
psi22=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/64)),I),I),I),I)*psi21;
psi22_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),H),I),I),I),I)*psi22;
psi23=kron(kron(kron(kron(CX(4,9),I),I),I),I)*psi22_5;
psi23_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),H),I),I),I),I)*psi23;
psi24=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/64),I),I),I),I),I),I),I),I),I)*psi23_5;
psi24_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),H),I),I),I),I)*psi24;
psi25=kron(kron(kron(kron(CX(4,9),I),I),I),I)*psi24_5;
psi25_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),I),H),I),I),I),I)*psi25;
psi26=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/64),I),I),I),I),I),I),I),I),I)*psi25_5;
%6p
psi27=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/32)),I),I),I),I),I)*psi26;
psi27_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),H),I),I),I),I),I)*psi27;
psi28=kron(kron(kron(kron(kron(CX(5,9),I),I),I),I),I)*psi27_5;
psi28_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),H),I),I),I),I),I)*psi28;
psi29=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/32),I),I),I),I),I),I),I),I),I)*psi28_5;
psi29_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),H),I),I),I),I),I)*psi29;
psi30=kron(kron(kron(kron(kron(CX(5,9),I),I),I),I),I)*psi29_5;
psi30_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),I),H),I),I),I),I),I)*psi30;
psi31=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/32),I),I),I),I),I),I),I),I),I)*psi30_5;
%7p
psi32=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/16)),I),I),I),I),I),I)*psi31;
psi32_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),H),I),I),I),I),I),I)*psi32;
psi33=kron(kron(kron(kron(kron(kron(CX(6,9),I),I),I),I),I),I)*psi32_5;
psi33_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),H),I),I),I),I),I),I)*psi33;
psi34=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/16),I),I),I),I),I),I),I),I),I)*psi33_5;
psi34_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),H),I),I),I),I),I),I)*psi34;
psi35=kron(kron(kron(kron(kron(kron(CX(6,9),I),I),I),I),I),I)*psi34_5;
psi35_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),I),H),I),I),I),I),I),I)*psi35;
psi36=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/16),I),I),I),I),I),I),I),I),I)*psi35_5;
%8p
psi37=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/8)),I),I),I),I),I),I),I)*psi36;
psi37_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),H),I),I),I),I),I),I),I)*psi37;
psi38=kron(kron(kron(kron(kron(kron(kron(CX(7,9),I),I),I),I),I),I),I)*psi37_5;
psi38_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),H),I),I),I),I),I),I),I)*psi38;
psi39=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/8),I),I),I),I),I),I),I),I),I)*psi38_5;
psi39_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),H),I),I),I),I),I),I),I)*psi39;
psi40=kron(kron(kron(kron(kron(kron(kron(CX(7,9),I),I),I),I),I),I),I)*psi39_5;
psi40_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,I),H),I),I),I),I),I),I),I)*psi40;
psi41=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/8),I),I),I),I),I),I),I),I),I)*psi40_5;
%9p
psi42=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/4)),I),I),I),I),I),I),I),I)*psi41;
psi42_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,H),I),I),I),I),I),I),I),I)*psi42;
psi43=kron(kron(kron(kron(kron(kron(kron(kron(CX(8,9),I),I),I),I),I),I),I),I)*psi42_5;
psi43_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,H),I),I),I),I),I),I),I),I)*psi43;
psi44=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(-pi/4),I),I),I),I),I),I),I),I),I)*psi43_5;
psi44_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,H),I),I),I),I),I),I),I),I)*psi44;
psi45=kron(kron(kron(kron(kron(kron(kron(kron(CX(8,9),I),I),I),I),I),I),I),I)*psi44_5;
psi45_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,H),I),I),I),I),I),I),I),I)*psi45;
psi46=kron(kron(kron(kron(kron(kron(kron(kron(kron(P(pi/4),I),I),I),I),I),I),I),I),I)*psi45_5;
%2h
psi47=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),I),I)*psi46;
%1p
psi48=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/512))*psi47;
psi48_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),I),H)*psi48;
psi49=kron(I,CX(0,8))*psi48_5;
psi49_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),I),H)*psi49;
psi50=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(-pi/512)),I),I),I),I),I),I),I),I)*psi49_5;
psi50_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),I),H)*psi50;
psi51=kron(I,CX(0,8))*psi50_5;
psi51_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),I),H)*psi51;
psi52=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/512)),I),I),I),I),I),I),I),I)*psi51_5;
%2p
psi53=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/256)),I)*psi52;
psi53_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),H),I)*psi53;
psi54=kron(kron(I,CX(1,8)),I)*psi53_5;
psi54_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),H),I)*psi54;
psi55=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(-pi/256)),I),I),I),I),I),I),I),I)*psi54_5;
psi55_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),H),I)*psi55;
psi56=kron(kron(I,CX(1,8)),I)*psi55_5;
psi56_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),I),H),I)*psi56;
psi57=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/256)),I),I),I),I),I),I),I),I)*psi56_5;
%3p
psi58=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/128)),I),I)*psi57;
psi58_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),H),I),I)*psi58;
psi59=kron(kron(kron(I,CX(2,8)),I),I)*psi58_5;
psi59_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),H),I),I)*psi59;
psi60=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(-pi/128)),I),I),I),I),I),I),I),I)*psi59_5;
psi60_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),H),I),I)*psi60;
psi61=kron(kron(kron(I,CX(2,8)),I),I)*psi60_5;
psi61_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),I),H),I),I)*psi61;
psi62=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/128)),I),I),I),I),I),I),I),I)*psi61_5;
%4p
psi63=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/64)),I),I),I)*psi62;
psi63_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),H),I),I),I)*psi63;
psi64=kron(kron(kron(kron(I,CX(3,8)),I),I),I)*psi63_5;
psi64_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),H),I),I),I)*psi64;
psi65=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(-pi/64)),I),I),I),I),I),I),I),I)*psi64_5;
psi65_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),H),I),I),I)*psi65;
psi66=kron(kron(kron(kron(I,CX(3,8)),I),I),I)*psi65_5;
psi66_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),I),H),I),I),I)*psi66;
psi67=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/64)),I),I),I),I),I),I),I),I)*psi66_5;
%5p
psi68=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/32)),I),I),I),I)*psi67;
psi68_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),H),I),I),I),I)*psi68;
psi69=kron(kron(kron(kron(kron(I,CX(4,8)),I),I),I),I)*psi68_5;
psi69_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),H),I),I),I),I)*psi69;
psi70=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(-pi/32)),I),I),I),I),I),I),I),I)*psi69_5;
psi70_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),H),I),I),I),I)*psi70;
psi71=kron(kron(kron(kron(kron(I,CX(4,8)),I),I),I),I)*psi70_5;
psi71_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),I),H),I),I),I),I)*psi71;
psi72=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/32)),I),I),I),I),I),I),I),I)*psi71_5;
%6p
psi73=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/16)),I),I),I),I),I)*psi72;
psi73_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),H),I),I),I),I),I)*psi73;
psi74=kron(kron(kron(kron(kron(kron(I,CX(5,8)),I),I),I),I),I)*psi73_5;
psi74_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),H),I),I),I),I),I)*psi74;
psi75=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(-pi/16)),I),I),I),I),I),I),I),I)*psi74_5;
psi75_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),H),I),I),I),I),I)*psi75;
psi76=kron(kron(kron(kron(kron(kron(I,CX(5,8)),I),I),I),I),I)*psi75_5;
psi76_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),I),H),I),I),I),I),I)*psi76;
psi77=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/16)),I),I),I),I),I),I),I),I)*psi76_5;
%7p
psi78=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/8)),I),I),I),I),I),I)*psi77;
psi78_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),H),I),I),I),I),I),I)*psi78;
psi79=kron(kron(kron(kron(kron(kron(kron(I,CX(6,8)),I),I),I),I),I),I)*psi78_5;
psi79_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),H),I),I),I),I),I),I)*psi79;
psi80=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(-pi/8)),I),I),I),I),I),I),I),I)*psi79_5;
psi80_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),H),I),I),I),I),I),I)*psi80;
psi81=kron(kron(kron(kron(kron(kron(kron(I,CX(6,8)),I),I),I),I),I),I)*psi80_5;
psi81_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),I),H),I),I),I),I),I),I)*psi81;
psi82=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/8)),I),I),I),I),I),I),I),I)*psi81_5;
%8p
psi83=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/4)),I),I),I),I),I),I),I)*psi82;
psi83_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),H),I),I),I),I),I),I),I)*psi83;
psi84=kron(kron(kron(kron(kron(kron(kron(kron(I,CX(7,8)),I),I),I),I),I),I),I)*psi83_5;
psi84_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),H),I),I),I),I),I),I),I)*psi84;
psi85=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(-pi/4)),I),I),I),I),I),I),I),I)*psi84_5;
psi85_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),H),I),I),I),I),I),I),I)*psi85;
psi86=kron(kron(kron(kron(kron(kron(kron(kron(I,CX(7,8)),I),I),I),I),I),I),I)*psi85_5;
psi86_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,H),H),I),I),I),I),I),I),I)*psi86;
psi87=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,P(pi/4)),I),I),I),I),I),I),I),I)*psi86_5;
%3h
psi88=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),I),I)*psi87;
%1p
psi89=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/256))*psi88;
psi89_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),I),H)*psi89;
psi90=kron(kron(I,I),CX(0,7))*psi89_5;
psi90_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),I),H)*psi90;
psi91=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(-pi/256)),I),I),I),I),I),I),I)*psi90_5;
psi91_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),I),H)*psi91;
psi92=kron(kron(I,I),CX(0,7))*psi91_5;
psi92_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),I),H)*psi92;
psi93=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/256)),I),I),I),I),I),I),I)*psi92_5;
%2p
psi94=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/128)),I)*psi93;
psi94_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),H),I)*psi94;
psi95=kron(kron(kron(I,I),CX(1,7)),I)*psi94_5;
psi95_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),H),I)*psi95;
psi96=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(-pi/128)),I),I),I),I),I),I),I)*psi95_5;
psi96_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),H),I)*psi96;
psi97=kron(kron(kron(I,I),CX(1,7)),I)*psi96_5;
psi97_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),I),H),I)*psi97;
psi98=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/128)),I),I),I),I),I),I),I)*psi97_5;
%3p
psi99=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/64)),I),I)*psi98;
psi99_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),H),I),I)*psi99;
psi100=kron(kron(kron(kron(I,I),CX(2,7)),I),I)*psi99_5;
psi100_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),H),I),I)*psi100;
psi101=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(-pi/64)),I),I),I),I),I),I),I)*psi100_5;
psi101_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),H),I),I)*psi101;
psi102=kron(kron(kron(kron(I,I),CX(2,7)),I),I)*psi101_5;
psi102_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),I),H),I),I)*psi102;
psi103=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/64)),I),I),I),I),I),I),I)*psi102_5;
%4p
psi104=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/32)),I),I),I)*psi103;
psi104_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),H),I),I),I)*psi104;
psi105=kron(kron(kron(kron(kron(I,I),CX(3,7)),I),I),I)*psi104_5;
psi105_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),H),I),I),I)*psi105;
psi106=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(-pi/32)),I),I),I),I),I),I),I)*psi105_5;
psi106_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),H),I),I),I)*psi106;
psi107=kron(kron(kron(kron(kron(I,I),CX(3,7)),I),I),I)*psi106_5;
psi107_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),I),H),I),I),I)*psi107;
psi108=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/32)),I),I),I),I),I),I),I)*psi107_5;
%5p
psi109=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/16)),I),I),I),I)*psi108;
psi109_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),H),I),I),I),I)*psi109;
psi110=kron(kron(kron(kron(kron(kron(I,I),CX(4,7)),I),I),I),I)*psi109_5;
psi110_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),H),I),I),I),I)*psi110;
psi111=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(-pi/16)),I),I),I),I),I),I),I)*psi110_5;
psi111_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),H),I),I),I),I)*psi111;
psi112=kron(kron(kron(kron(kron(kron(I,I),CX(4,7)),I),I),I),I)*psi111_5;
psi112_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),I),H),I),I),I),I)*psi112;
psi113=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/16)),I),I),I),I),I),I),I)*psi112_5;
%6p
psi114=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/8)),I),I),I),I),I)*psi113;
psi114_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),H),I),I),I),I),I)*psi114;
psi115=kron(kron(kron(kron(kron(kron(kron(I,I),CX(5,7)),I),I),I),I),I)*psi114_5;
psi115_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),H),I),I),I),I),I)*psi115;
psi116=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(-pi/8)),I),I),I),I),I),I),I)*psi115_5;
psi116_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),H),I),I),I),I),I)*psi116;
psi117=kron(kron(kron(kron(kron(kron(kron(I,I),CX(5,7)),I),I),I),I),I)*psi116_5;
psi117_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),I),H),I),I),I),I),I)*psi117;
psi118=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/8)),I),I),I),I),I),I),I)*psi117_5;
%7p
psi119=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/4)),I),I),I),I),I),I)*psi118;
psi119_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),H),I),I),I),I),I),I)*psi119;
psi120=kron(kron(kron(kron(kron(kron(kron(kron(I,I),CX(6,7)),I),I),I),I),I),I)*psi119_5;
psi120_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),H),I),I),I),I),I),I)*psi120;
psi121=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(-pi/4)),I),I),I),I),I),I),I)*psi120_5;
psi121_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),H),I),I),I),I),I),I)*psi121;
psi122=kron(kron(kron(kron(kron(kron(kron(kron(I,I),CX(6,7)),I),I),I),I),I),I)*psi121_5;
psi122_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),H),H),I),I),I),I),I),I)*psi122;
psi123=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),P(pi/4)),I),I),I),I),I),I),I)*psi122_5;
%4h
psi124=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),I),I)*psi123;
%1p
psi125=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/128))*psi124;
psi125_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),I),H)*psi125;
psi126=kron(kron(kron(I,I),I),CX(0,6))*psi125_5;
psi126_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),I),H)*psi126;
psi127=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(-pi/128)),I),I),I),I),I),I)*psi126_5;
psi127_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),I),H)*psi127;
psi128=kron(kron(kron(I,I),I),CX(0,6))*psi127_5;
psi128_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),I),H)*psi128;
psi129=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/128)),I),I),I),I),I),I)*psi128_5;
%2p
psi130=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/64)),I)*psi129;
psi130_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),H),I)*psi130;
psi131=kron(kron(kron(kron(I,I),I),CX(1,6)),I)*psi130_5;
psi131_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),H),I)*psi131;
psi132=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(-pi/64)),I),I),I),I),I),I)*psi131_5;
psi132_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),H),I)*psi132;
psi133=kron(kron(kron(kron(I,I),I),CX(1,6)),I)*psi132_5;
psi133_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),I),H),I)*psi133;
psi134=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/64)),I),I),I),I),I),I)*psi133_5;
%3p
psi135=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/32)),I),I)*psi134;
psi135_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),H),I),I)*psi135;
psi136=kron(kron(kron(kron(kron(I,I),I),CX(2,6)),I),I)*psi135_5;
psi136_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),H),I),I)*psi136;
psi137=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(-pi/32)),I),I),I),I),I),I)*psi136_5;
psi137_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),H),I),I)*psi137;
psi138=kron(kron(kron(kron(kron(I,I),I),CX(2,6)),I),I)*psi137_5;
psi138_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),I),H),I),I)*psi138;
psi139=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/32)),I),I),I),I),I),I)*psi138_5;
%4p
psi140=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/16)),I),I),I)*psi139;
psi140_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),H),I),I),I)*psi140;
psi141=kron(kron(kron(kron(kron(kron(I,I),I),CX(3,6)),I),I),I)*psi140_5;
psi141_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),H),I),I),I)*psi141;
psi142=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(-pi/16)),I),I),I),I),I),I)*psi141_5;
psi142_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),H),I),I),I)*psi142;
psi143=kron(kron(kron(kron(kron(kron(I,I),I),CX(3,6)),I),I),I)*psi142_5;
psi143_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),I),H),I),I),I)*psi143;
psi144=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/16)),I),I),I),I),I),I)*psi143_5;
%5p
psi145=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/8)),I),I),I),I)*psi144;
psi145_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),H),I),I),I),I)*psi145;
psi146=kron(kron(kron(kron(kron(kron(kron(I,I),I),CX(4,6)),I),I),I),I)*psi145_5;
psi146_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),H),I),I),I),I)*psi146;
psi147=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(-pi/8)),I),I),I),I),I),I)*psi146_5;
psi147_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),H),I),I),I),I)*psi147;
psi148=kron(kron(kron(kron(kron(kron(kron(I,I),I),CX(4,6)),I),I),I),I)*psi147_5;
psi148_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),I),H),I),I),I),I)*psi148;
psi149=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/8)),I),I),I),I),I),I)*psi148_5;
%6p
psi150=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/4)),I),I),I),I),I)*psi149;
psi150_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),H),I),I),I),I),I)*psi150;
psi151=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),CX(5,6)),I),I),I),I),I)*psi150_5;
psi151_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),H),I),I),I),I),I)*psi151;
psi152=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(-pi/4)),I),I),I),I),I),I)*psi151_5;
psi152_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),H),I),I),I),I),I)*psi152;
psi153=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),CX(5,6)),I),I),I),I),I)*psi152_5;
psi153_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),H),I),I),I),I),I)*psi153;
psi154=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),P(pi/4)),I),I),I),I),I),I)*psi153_5;
%5h
psi155=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),I),I)*psi154;
%1p
psi156=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/64))*psi155;
psi156_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),I),H)*psi156;
psi157=kron(kron(kron(kron(I,I),I),I),CX(0,5))*psi156_5;
psi157_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),I),H)*psi157;
psi158=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(-pi/64)),I),I),I),I),I)*psi157_5;
psi158_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),I),H)*psi158;
psi159=kron(kron(kron(kron(I,I),I),I),CX(0,5))*psi158_5;
psi159_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),I),H)*psi159;
psi160=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/64)),I),I),I),I),I)*psi159_5;
%2p
psi161=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/32)),I)*psi160;
psi161_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),H),I)*psi161;
psi162=kron(kron(kron(kron(kron(I,I),I),I),CX(1,5)),I)*psi161_5;
psi162_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),H),I)*psi162;
psi163=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(-pi/32)),I),I),I),I),I)*psi162_5;
psi163_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),H),I)*psi163;
psi164=kron(kron(kron(kron(kron(I,I),I),I),CX(1,5)),I)*psi163_5;
psi164_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),I),H),I)*psi164;
psi165=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/32)),I),I),I),I),I)*psi164_5;
%3p
psi166=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/16)),I),I)*psi165;
psi166_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),H),I),I)*psi166;
psi167=kron(kron(kron(kron(kron(kron(I,I),I),I),CX(2,5)),I),I)*psi166_5;
psi167_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),H),I),I)*psi167;
psi168=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(-pi/16)),I),I),I),I),I)*psi167_5;
psi168_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),H),I),I)*psi168;
psi169=kron(kron(kron(kron(kron(kron(I,I),I),I),CX(2,5)),I),I)*psi168_5;
psi169_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),I),H),I),I)*psi169;
psi170=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/16)),I),I),I),I),I)*psi169_5;
%4p
psi171=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/8)),I),I),I)*psi170;
psi171_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),H),I),I),I)*psi171;
psi172=kron(kron(kron(kron(kron(kron(kron(I,I),I),I),CX(3,5)),I),I),I)*psi171_5;
psi172_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),H),I),I),I)*psi172;
psi173=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(-pi/8)),I),I),I),I),I)*psi172_5;
psi173_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),H),I),I),I)*psi173;
psi174=kron(kron(kron(kron(kron(kron(kron(I,I),I),I),CX(3,5)),I),I),I)*psi173_5;
psi174_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),I),H),I),I),I)*psi174;
psi175=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/8)),I),I),I),I),I)*psi174_5;
%5p
psi176=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/4)),I),I),I),I)*psi175;
psi176_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),H),I),I),I),I)*psi176;
psi177=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),CX(4,5)),I),I),I),I)*psi176_5;
psi177_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),H),I),I),I),I)*psi177;
psi178=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(-pi/4)),I),I),I),I),I)*psi177_5;
psi178_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),H),I),I),I),I)*psi178;
psi179=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),CX(4,5)),I),I),I),I)*psi178_5;
psi179_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),H),I),I),I),I)*psi179;
psi180=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),P(pi/4)),I),I),I),I),I)*psi179_5;
%6h
psi181=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),I),I)*psi180;
%1p
psi182=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/32))*psi181;
psi182_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),I),H)*psi182;
psi183=kron(kron(kron(kron(kron(I,I),I),I),I),CX(0,4))*psi182_5;
psi183_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),I),H)*psi183;
psi184=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(-pi/32)),I),I),I),I)*psi183_5;
psi184_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),I),H)*psi184;
psi185=kron(kron(kron(kron(kron(I,I),I),I),I),CX(0,4))*psi184_5;
psi185_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),I),H)*psi185;
psi186=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/32)),I),I),I),I)*psi185_5;
%2p
psi187=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/16)),I)*psi186;
psi187_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),H),I)*psi187;
psi188=kron(kron(kron(kron(kron(kron(I,I),I),I),I),CX(1,4)),I)*psi187_5;
psi188_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),H),I)*psi188;
psi189=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(-pi/16)),I),I),I),I)*psi188_5;
psi189_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),H),I)*psi189;
psi190=kron(kron(kron(kron(kron(kron(I,I),I),I),I),CX(1,4)),I)*psi189_5;
psi190_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),I),H),I)*psi190;
psi191=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/16)),I),I),I),I)*psi190_5;
%3p
psi192=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/8)),I),I)*psi191;
psi192_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),H),I),I)*psi192;
psi193=kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),CX(2,4)),I),I)*psi192_5;
psi193_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),H),I),I)*psi193;
psi194=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(-pi/8)),I),I),I),I)*psi193_5;
psi194_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),H),I),I)*psi194;
psi195=kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),CX(2,4)),I),I)*psi194_5;
psi195_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),I),H),I),I)*psi195;
psi196=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/8)),I),I),I),I)*psi195_5;
%4p
psi197=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/4)),I),I),I)*psi196;
psi197_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),H),I),I),I)*psi197;
psi198=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),CX(3,4)),I),I),I)*psi197_5;
psi198_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),H),I),I),I)*psi198;
psi199=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(-pi/4)),I),I),I),I)*psi198_5;
psi199_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),H),I),I),I)*psi199;
psi200=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),CX(3,4)),I),I),I)*psi199_5;
psi200_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),H),H),I),I),I)*psi200;
psi201=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),P(pi/4)),I),I),I),I)*psi200_5;
%7h
psi202=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),I),I)*psi201;
%1p
psi203=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/16))*psi202;
psi203_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),I),H)*psi203;
psi204=kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),CX(0,3))*psi203_5;
psi204_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),I),H)*psi204;
psi205=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(-pi/16)),I),I),I)*psi204_5;
psi205_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),I),H)*psi205;
psi206=kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),CX(0,3))*psi205_5;
psi206_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),I),H)*psi206;
psi207=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/16)),I),I),I)*psi206_5;
%2p
psi208=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/8)),I)*psi207;
psi208_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),H),I)*psi208;
psi209=kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),CX(1,3)),I)*psi208_5;
psi209_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),H),I)*psi209;
psi210=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(-pi/8)),I),I),I)*psi209_5;
psi210_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),H),I)*psi210;
psi211=kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),CX(1,3)),I)*psi210_5;
psi211_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),I),H),I)*psi211;
psi212=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/8)),I),I),I)*psi211_5;
%3p
psi213=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/4)),I),I)*psi212;
psi213_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),H),I),I)*psi213;
psi214=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),CX(2,3)),I),I)*psi213_5;
psi214_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),H),I),I)*psi214;
psi215=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(-pi/4)),I),I),I)*psi214_5;
psi215_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),H),I),I)*psi215;
psi216=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),CX(2,3)),I),I)*psi215_5;
psi216_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),H),H),I),I)*psi216;
psi217=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),P(pi/4)),I),I),I)*psi216_5;
%8h
psi218=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),I),I)*psi217;
%1p
psi219=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/8))*psi218;
psi219_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),I),H)*psi219;
psi220=kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),CX(0,2))*psi219_5;
psi220_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),I),H)*psi220;
psi221=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(-pi/8)),I),I)*psi220_5;
psi221_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),I),H)*psi221;
psi222=kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),CX(0,2))*psi221_5;
psi222_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),I),H)*psi222;
psi223=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/8)),I),I)*psi222_5;
%2p
psi224=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/4)),I)*psi223;
psi224_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),H),I)*psi224;
psi225=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),CX(1,2)),I)*psi224_5;
psi225_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),H),I)*psi225;
psi226=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(-pi/4)),I),I)*psi225_5;
psi226_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),H),I)*psi226;
psi227=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),CX(1,2)),I)*psi226_5;
psi227_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),H),H),I)*psi227;
psi228=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),P(pi/4)),I),I)*psi227_5;
%9h
psi229=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),H),I)*psi228;
%1p
psi230=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),P(pi/4))*psi229;
psi230_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),H),H)*psi230;
psi231=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),CX(0,1))*psi230_5;
psi231_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),H),H)*psi231;
psi232=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(-pi/4)),I)*psi231_5;
psi232_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),H),H)*psi232;
psi233=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),CX(0,1))*psi232_5;
psi233_5=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),H),H)*psi233;
psi234=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),P(pi/4)),I)*psi233_5;
%10h
psi235=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),I),I),I),I),I),H)*psi234;
%SWAPS
psi236=CX(0,9)*psi235;
psi237=kron(kron(I,CX(1,8)),I)*psi236;
psi238=kron(kron(kron(kron(I,I),CX(2,7)),I),I)*psi237;
psi239=kron(kron(kron(kron(kron(kron(I,I),I),CX(3,6)),I),I),I)*psi238;
psi240=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),CX(4,5)),I),I),I),I)*psi239;
psi241=kron(kron(kron(kron(kron(kron(kron(kron(kron(H,H),H),H),H),H),H),H),H),H)*psi240;
psi242=CX(0,9)*psi241;
psi243=kron(kron(H,CX(1,8)),H)*psi242;
psi244=kron(kron(kron(kron(I,H),CX(2,7)),H),I)*psi243;
psi245=kron(kron(kron(kron(kron(kron(I,I),H),CX(3,6)),H),I),I)*psi244;
psi246=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),H),CX(4,5)),H),I),I),I)*psi245;
psi247=kron(kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),H),H),I),I),I),I)*psi246;
psi248=CX(0,9)*psi247;
psi249=kron(kron(I,CX(1,8)),I)*psi248;
psi250=kron(kron(kron(kron(I,I),CX(2,7)),I),I)*psi249;
psi251=kron(kron(kron(kron(kron(kron(I,I),I),CX(3,6)),I),I),I)*psi250;
psi252=kron(kron(kron(kron(kron(kron(kron(kron(I,I),I),I),CX(4,5)),I),I),I),I)*psi251;
histogram2(psi252)

